### ISSUE TITLE
invalid_client

### ISSUE THREAD

**Issue by AlienQueen** [lunarok/jeedom_flowerpowerbt#3]
Hi,

Since october, I have no sync to Parrot anymore. I tried connecting to /urlencoded /user/v4/authenticate but it doesn't work either. Please advice.

Here's my log:

POST/urlencoded /user/v3/authenticate
client_id: XXX
client_secret: XXX
username: XXX
password: XXX
grant_type: password
app_identifier:
{ headers:
{ 'Content-Type': 'application/x-www-form-urlencoded',
Authorization: '' },
body: 'client_id=XXX&client_secret=XXX&username=XXX&password=XXX&grant_type=password&app_identifier=',
url: 'https://api-flower-power-pot.parrot.com/user/v3/authenticate',
method: 'POST' }
CODE: 400
error: invalid_client

**Comment by lunarok** [comment]
see documentation, Parrot has change their server, new API, new key required so, it's in the doc

**Comment by AlienQueen** [comment]
Sorry...

**Comment by AlienQueen** [comment]
https://jeedom.github.io/documentation/plugins/flowerpowerbt/fr_FR/index.html gives 404

**Comment by lunarok** [comment]
https://github.com/lunarok/jeedom_flowerpowerbt/blob/master/doc/fr_FR/configuration.asciidoc

don't know why the doc is not created, have report it

**Comment by AlienQueen** [comment]
Thanks. Sorry about the noise.

**Comment by lunarok** [comment]
no, at least I see the doc is not created and can check why so it will be avalaible for everyone
